checklist:
  zones:
    - title: "Devolpment"
      tasks:
        - name: "Check Web Status"
          check: "web-status-dev"
          importancia: "High"
        - name: "Check Alt Web Status"
          check: "web-status-dev"
          importancia: "High"
        - name: "Check Mysql Database Status"
          check: "sql-status-dev"
          importancia: "Low"
        - name: "Check Mysql Database User"
          check: "sql-user-dev"
          importancia: "High"
    
    - title: "Production"
      tasks:
        - name: "Check Web Status"
          check: "web-status-prod"
          importancia: "High"
        - name: "Check Alt Web Status"
          check: "web-status-prod"
          importancia: "High"
        - name: "Check Mysql Database Status"
          check: "sql-status-prod"
          importancia: "Low"
        - name: "Check Mysql Database User"
          check: "sql-user-prod"
          importancia: "High"

enviroment:
  servers:
    - name: "Devolpment"
      type: "ubuntu_22.04"
      hostname: "localhost"      
      ip: "127.0.0.1"
      sql_port: 3160
      web_port: 443
      web_port_2: 8443
    - name: "Production"
      type: "ubuntu_22.04"
      hostname: "hola.com"
      ip: "15.216.186.116"
      sql_port: 3160
      web_port: 443
      web_port_2: 8443


